const SpotifyTypes = {
  CONNECT_FAILURE: 'CONNECT_FAILURE',
  CHECK_CONNECTION: 'CHECK_CONNECTION',
  MARK_CONNECTED: 'MARK_CONNECTED',
  REFRESH_AUTH_TOKEN_START: 'REFRESH_AUTH_TOKEN_START',
  REFRESH_AUTH_TOKEN_SUCCESS: 'REFRESH_AUTH_TOKEN_SUCCESS',
  REFRESH_AUTH_TOKEN_FAILURE: 'REFRESH_AUTH_TOKEN_FAILURE',
  FETCH_TOP_ARTISTS_START: 'FETCH_TOP_ARTISTS_START',
  FETCH_TOP_ARTISTS_SUCCESS: 'FETCH_TOP_ARTISTS_SUCCESS',
  FETCH_TOP_ARTISTS_FAILURE: 'FETCH_TOP_ARTISTS_FAILURE',
};

export default SpotifyTypes;
