const SpotifyTypes = {
  CONNECT_FAILURE: 'CONNECT_FAILURE',
  CHECK_CONNECTION: 'CHECK_CONNECTION',
  MARK_CONNECTED: 'MARK_CONNECTED',
  FETCH_USER_INFO_START: 'FETCH_USER_INFO_START',
  FETCH_USER_INFO_SUCCESS: 'FETCH_USER_INFO_SUCCESS',
  FETCH_USER_INFO_FAILURE: 'FETCH_USER_INFO_FAILURE',
  REFRESH_AUTH_TOKEN_START: 'REFRESH_AUTH_TOKEN_START',
  REFRESH_AUTH_TOKEN_SUCCESS: 'REFRESH_AUTH_TOKEN_SUCCESS',
  REFRESH_AUTH_TOKEN_FAILURE: 'REFRESH_AUTH_TOKEN_FAILURE',
  FETCH_TOP_ARTISTS_LONG_TERM_START: 'FETCH_TOP_ARTISTS_LONG_TERM_START',
  FETCH_TOP_ARTISTS_MEDIUM_TERM_START: 'FETCH_TOP_ARTISTS_MEDIUM_TERM_START',
  FETCH_TOP_ARTISTS_SHORT_TERM_START: 'FETCH_TOP_ARTISTS_SHORT_TERM_START',
  FETCH_TOP_ARTISTS_LONG_TERM_SUCCESS: 'FETCH_TOP_ARTISTS_LONG_TERM_SUCCESS',
  FETCH_TOP_ARTISTS_MEDIUM_TERM_SUCCESS:
    'FETCH_TOP_ARTISTS_MEDIUM_TERM_SUCCESS',
  FETCH_TOP_ARTISTS_SHORT_TERM_SUCCESS: 'FETCH_TOP_ARTISTS_SHORT_TERM_SUCCESS',
  FETCH_TOP_ARTISTS_FAILURE: 'FETCH_TOP_ARTISTS_FAILURE',
  FETCH_TOP_TRACKS_LONG_TERM_START: 'FETCH_TOP_TRACKS_LONG_TERM_START',
  FETCH_TOP_TRACKS_MEDIUM_TERM_START: 'FETCH_TOP_TRACKS_MEDIUM_TERM_START',
  FETCH_TOP_TRACKS_SHORT_TERM_START: 'FETCH_TOP_TRACKS_SHORT_TERM_START',
  FETCH_TOP_TRACKS_LONG_TERM_SUCCESS: 'FETCH_TOP_TRACKS_LONG_TERM_SUCCESS',
  FETCH_TOP_TRACKS_MEDIUM_TERM_SUCCESS: 'FETCH_TOP_TRACKS_MEDIUM_TERM_SUCCESS',
  FETCH_TOP_TRACKS_SHORT_TERM_SUCCESS: 'FETCH_TOP_TRACKS_SHORT_TERM_SUCCESS',
  FETCH_TOP_TRACKS_FAILURE: 'FETCH_TOP_TRACKS_FAILURE',
  DISCONNECT_START: 'DISCONNECT_START',
  DISCONNECT_SUCCESS: 'DISCONNECT_SUCCESS',
  DISCONNECT_FAILURE: 'DISCONNECT_FAILURE'
};

export default SpotifyTypes;
